import { router } from "./router";
import { buttonComp } from "./components/button-comp";
import { textComp } from "./components/text-comp";
import { inputComp } from "./components/input-comp";
import { cardComp } from "./components/card-comp";
import { headerComp } from "./components/header-comp";
import { homePage } from "./pages/home-page";
import { petLostPage } from "./pages/pet-lost-page";
import { initPage } from "./pages/init-page";
import { loginPage } from "./pages/login-page";
import { registPage } from "./pages/regist-page";
import { perfilPage } from "./pages/perfil-page";
import { dataPage } from "./pages/mis-datos-page";
import { passPage } from "./pages/mi-pass-page";
(function main() {
	router;
	buttonComp();
	textComp();
	inputComp();
	cardComp();
	headerComp();
	homePage();
	petLostPage();
	initPage();
	loginPage();
	registPage();
	perfilPage();
	dataPage();
	passPage();
})();
