import { router } from "./router";
import { buttonComp } from "./components/button-comp";
import { textComp } from "./components/text-comp";
import { inputComp } from "./components/input-comp";
import { cardComp } from "./components/card-comp";
import { headerComp } from "./components/header-comp";
import { messageComp } from "./components/message-comp";
import { loadComp } from "./components/load-comp";
import { homePage } from "./pages/home/home-page";
import { shareLocPage } from "./pages/home/share-loc-page";
import { petLostPage } from "./pages/home/pet-lost-page";
import { loginPage } from "./pages/auth/login-page";
import { registPage } from "./pages/auth/regist-page";
import { perfilPage } from "./pages/perfil-page";
import { dataPage } from "./pages/profile/my-data-page";
import { passPage } from "./pages/profile/my-pass-page";
import { enterEmailPage } from "./pages/restore-pass/enter-email";
import { enterCodePage } from "./pages/restore-pass/enter-code";
import { reportPage } from "./pages/report-page";
import { editReportPage } from "./pages/edit-report-page";
import { myReportsPage } from "./pages/my-reports-page";
import { state } from "./state";
(function main() {
  state.init();
  router;
  buttonComp();
  textComp();
  inputComp();
  cardComp();
  headerComp();
  messageComp();
  loadComp();
  homePage();
  shareLocPage();
  petLostPage();
  loginPage();
  registPage();
  perfilPage();
  dataPage();
  passPage();
  enterEmailPage();
  enterCodePage();
  reportPage();
  editReportPage();
  myReportsPage();
})();
